server:
  port: 8082
zuul:
  routes:
    service:
      path: /command/**
      serviceId: integration-service
      ribbon:
        ConnectTimeout: 120000
        ReadTimeout: 120000
---
spring:
  profiles: kubernetes