version: '3'

services:

  integration-config-service:
    build:
      context: ./integration-config-server
      dockerfile: Dockerfile
    image: integration-cloud-native/integration-config-server:latest
    ports:
      - 8888:8888
    networks:
      integration-cloud-network:
    environment:
      SPRING_PROFILES_ACTIVE: stage
      GIT_CONFIG_URI: https://github.com/shahroozsabet/fleetmonitor-config.git

  integration-service-discovery:
    build:
      context: ./integration-service-discovery
      dockerfile: Dockerfile
    image: fleetmonitor/integration-service-discovery:latest
    ports:
      - 8761:8761
    networks:
      integration-cloud-network:
    depends_on:
      - integration-config-service

  integration-gateway:
    build:
      context: ./integration-gateway
      dockerfile: Dockerfile
    image: fleetmonitor/integration-gateway:latest
    ports:
      - 8082:8082
    networks:
      integration-cloud-network:
    depends_on:
      - integration-service-discovery
      - integration-config-service
    environment:

      SPRING_PROFILES_ACTIVE: stage,cors
      DISCOVERY_SERVICE_HOST: integration-service-discovery
      DISCOVERY_SERVICE_PORT: 8761

  integration-service:
    build:
      context: ./integration-service
      dockerfile: Dockerfile
    image: fleetmonitor/integration-service:latest
    ports:
      - 8090:8090
    networks:
      integration-cloud-network:
    depends_on:
      - integration-service-discovery
      - integration-config-service
    environment:
      SPRING_PROFILES_ACTIVE: stage
      DISCOVERY_SERVICE_HOST: integration-service-discovery
      DISCOVERY_SERVICE_PORT: 8761
      CONFIG_SERVICE_HOST: integration-config-service
      CONFIG_SERVICE_PORT: 8888

networks:
  integration-cloud-network: