apiVersion: v1
kind: Service
metadata:
  name: integration-gateway-service-exposed
spec:
  type: NodePort
  selector:
    app: integration-gateway
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 30012