spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
server:
  port: 8090
---
spring:
  profiles: dev
logging:
  level:
    org:
      springframework:
        web: DEBUG
---
spring:
  profiles: dev-cloud
server:
  port: 0
---
spring:
  profiles: prod
server:
  port: 8080    